if has("gui_mac") || has("gui_macvim")
    set guifont=Andale\ Mono:h18
    " key binding for Command-T to behave properly
    " uncomment to replace the Mac Command-T key to Command-T plugin
    macmenu &File.New\ Tab key=<nop>
    map <D-t> :CommandT<CR>
    map <D-r> :CommandT<CR>
    " make Mac's Option key behave as the Meta key
    set invmmta
    try
      set transparency=1
    catch
    endtry
endif

" I can't help it.  I still like this plugin
source ~/dotfiles/vim/minibufexpl.vim
