"Use Vim settings, rather then Vi settings (much better!).
"This must be first, because it changes other options as a side effect.
set nocompatible

set guioptions-=T                         " turn toobar off
set guioptions-=m                         " turn menu off by default

"Toggle menu on/off
map <silent> <C-F2> :if &guioptions =~# 'm' <Bar>
                    \set guioptions-=m <Bar>
                    \else <Bar>
                    \set guioptions+=m <Bar>
                    \endif<CR>

set number                                " turn on line numbers
set lines=50                              " set window height
set columns=130                           " set window width
set lcs=tab:>.,trail:·,nbsp:%             " set trailing (invisible) characters
set list                                  " show invisible characters
set cursorline

"custom status line (across the bottom of the screen)
" See http://vimdoc.sourceforge.net/htmldoc/options.html#'statusline' for more
" details on statusline (blatantly stolen from Joe Fiorini)
set statusline=%F%m%r%h%w\ [TYPE=%Y]\ \ \ \ \ \ \ \ \ \ \ \ [POS=%2l,%2v][%p%%]\ \ \ \ \ \ \ \ \ \ \ \ [LEN=%L]
set laststatus=2                          " show status line

" windows font
if has("win32") || has("gui_win32s")
  set guifont=Consolas:h14:cANSI          " set font for windows
endif

" mac font
if has("gui_mac") || has("gui_macvim")
    set guifont=Andale\ Mono:h18          " set font for mac

    " key binding for Command-T to behave properly
    " uncomment to replace the Mac Command-T key to Command-T plugin
    macmenu &File.New\ Tab key=<nop>
    map <D-t> :CommandT<CR>
    map <D-r> :CommandT<CR>
    " make Mac's Option key behave as the Meta key
    set invmmta
    try
      set transparency=1
    catch
    endtry
endif

syntax enable
set background=light
colorscheme solarized                     " set colorscheme
"syntax on                                 " syntax color highlighting

set softtabstop=2                         " number of spaces in soft tab
set shiftwidth=2                          " number of spaces to shift <>
set tabstop=2                             " number of spaces to show for tab
set expandtab                             " use spaces instead of tabs
set autoindent                            " auto indent is on
set ignorecase                            " ???
set backspace=indent,eol,start            " backspace over everything
set history=1000                          " store lots of :cmdline history

" Make tabs work like we're used to
map <C-Tab> :tabnext<CR>
map <C-S-Tab> :tabprev<CR>

if has("win32") || has("gui_win32s")
  set directory=c:\\TEMP                  " set directory for swap files (e.g. file.rb.swp)
  set backupdir=c:\\TEMP                  " set directory for backup files (e.g. file.rb~)
else
  set directory=/tmp                      " set directory for swap files (e.g. file.rb.swp)
  set backupdir=/tmp                      " set directory for backup files (e.g. file.rb~)
endif

" I can't help it.  I still like this plugin
source ~/dotfiles/vim/minibufexpl.vim
